import { chromium } from 'playwright';
const proxy = process.env.HTTPS_PROXY;
const b = await chromium.launch({ proxy: { server: proxy, bypass: '<-loopback>,localhost,127.0.0.1' } });
const p = await b.newPage({ viewport: { width: 1440, height: 980 } });
p.on('console', m => console.log('[console]', m.type(), m.text().slice(0,200)));
p.on('pageerror', e => console.log('[pageerror]', String(e).slice(0,300)));
p.on('requestfailed', r => console.log('[reqfail]', r.url().slice(0,90), r.failure()?.errorText));
await p.goto('http://localhost:8137/index.html#/overview', { waitUntil: 'load' });
await p.waitForTimeout(3500);
console.log('L defined:', await p.evaluate(() => typeof window.L));
console.log('map panes:', await p.evaluate(() => document.querySelectorAll('.leaflet-marker-icon').length));
console.log('tiles:', await p.evaluate(() => document.querySelectorAll('.leaflet-tile').length));
console.log('canvas size:', await p.evaluate(() => { const e=document.querySelector('.map-canvas'); return e? e.clientWidth+'x'+e.clientHeight : 'none'; }));
console.log('bubbles html:', await p.evaluate(() => document.querySelector('.cluster-bubble')?.outerHTML?.slice(0,120) || 'none'));
console.log('band:', await p.evaluate(() => { const e=document.querySelector('.map-band'); const cs=getComputedStyle(e); return JSON.stringify({cls:e.className, h:cs.height, pos:cs.position, disp:cs.display, client:e.clientHeight}); }));
console.log('parent:', await p.evaluate(() => { const e=document.querySelector('.map-band').parentElement; const cs=getComputedStyle(e); return JSON.stringify({tag:e.tagName, cls:e.className, h:cs.height, client:e.clientHeight}); }));
console.log('canvas cs:', await p.evaluate(() => { const e=document.querySelector('.map-canvas'); const cs=getComputedStyle(e); return JSON.stringify({cls:e.className, pos:cs.position, inset:cs.inset, top:cs.top, bottom:cs.bottom, h:cs.height, parent:e.parentElement.className}); }));
await b.close();
